### ISSUE TITLE
New Memory address for DF Matched - No Issue

### ISSUE THREAD

**Issue by r4nm4** [devunt/DFAssist#25]
Hi guys,
as always with new patch (3.4 in that case) new memory address :)

From my test, if can be helpful, the new address for DF matched become from "0x0339" to "0x0080".
Thank you for your amazing app!
Cheers :)

**Comment by devunt** [comment]
Hi!

Thank you for the information.
I have a plan to add support for a global version of FFXIV, but since I don't have a test account on global server I have no idea whether the program will run smoothly without problems or not.
I'll keep this information for future reference and use it when adding the global version support.

**Comment by r4nm4** [comment]
Omg this is an awesome news!!!
Well done! :)
